# Generated by Django 4.2.13 on 2024-08-27 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('start_text', models.TextField(blank=True, null=True)),
                ('system_text', models.TextField(blank=True, null=True)),
                ('telegram_whitelist', models.TextField(blank=True, null=True)),
                ('telegram_token', models.CharField(max_length=100)),
                ('is_whitelist_enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant_bot.bot')),
            ],
        ),
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogs', to='assistant_bot.instance')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('cost_details', models.JSONField(blank=True, default=dict)),
                ('cost', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant_bot.dialog')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant_bot.role')),
            ],
            options={
                'unique_together': {('dialog', 'message_id')},
            },
        ),
    ]
