# Generated by Django 4.2.13 on 2024-10-15 10:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_bot', '0002_remove_dialog_and_message_and_instance'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'unique_together': {('user_id', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant_bot.bot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant_bot.botuser')),
            ],
        ),
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogs', to='assistant_bot.instance')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('cost_details', models.JSONField(blank=True, default=dict)),
                ('cost', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant_bot.dialog')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant_bot.role')),
            ],
            options={
                'unique_together': {('dialog', 'message_id')},
            },
        ),
    ]
