# Generated by Django 4.2.13 on 2025-03-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_bot', '0004_message_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='telegram_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
