# Generated by Django 4.2.13 on 2024-08-27 15:10

from django.db import migrations, models, connection
import django.db.models.deletion
import mptt.fields
import pgvector.django


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# storage.migrations.0001_initial_squashed

def create_pgvector_extension(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute('CREATE EXTENSION IF NOT EXISTS vector;')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistant_bot', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_pgvector_extension
        ),
        migrations.CreateModel(
            name='WikiDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                          related_name='wikis', to='assistant_bot.bot')),
                ('url', models.URLField(blank=True, null=True)),
                ('title', models.TextField(blank=True)),
                ('description', models.TextField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent',
                 mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                            related_name='children', to='assistant_storage.wikidocument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WikiDocumentProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiki_document',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing',
                                   to='assistant_storage.wikidocument')),
                ('status', models.CharField(
                    choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('failed', 'Failed')],
                    default='in_progress', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
                ('wiki', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                           related_name='documents', to='assistant_storage.wikidocument')),
                ('processing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='assistant_storage.wikidocumentprocessing'))
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('embedding', pgvector.django.VectorField(blank=True, dimensions=768, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='assistant_storage.document')),
            ],
            options={
                'indexes': [pgvector.django.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='question_embedding_index', opclasses=['vector_cosine_ops'])],
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('embedding', pgvector.django.VectorField(blank=True, dimensions=768, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='assistant_storage.document')),
            ],
            options={
                'indexes': [pgvector.django.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='sentence_embedding_index', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
