# Generated by Django 4.2.13 on 2024-10-10 12:00

from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content_embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AlterField(
            model_name='wikidocument',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='wikidocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='wikidocument',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='wikidocument',
            name='title',
            field=models.TextField(blank=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='wikidocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='wikidocument',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
